import os
import sys
import subprocess
import requests
import json
from datetime import datetime
from . import config

def get_crontab_info():
    try:
        # Get current user's crontab
        result = subprocess.run(['crontab', '-l'], capture_output=True, text=True)
        if result.returncode != 0:
            # Fallback for when crontab -l fails (e.g. permission denied or no cron)
            # Just return a message saying we can't read it but report the file path we WOULD use
            return "Unable to read system crontab (Permission Denied or Empty). Please check manually."
        
        cron_lines = result.stdout.strip().split('\n')
        # Filter out comments and empty lines
        active_jobs = [line for line in cron_lines if line.strip() and not line.strip().startswith('#')]
        
        if not active_jobs:
            return "No active cron jobs found."
            
        return "\n".join(active_jobs)
    except Exception as e:
        return f"Error retrieving crontab: {e}"

def send_feishu_report():
    webhook_url = config.FEISHU_WEBHOOK_URL
    if not webhook_url:
        print("Error: FEISHU_WEBHOOK_URL not configured in .env")
        return

    # Gather System Info
    current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    project_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    script_path = os.path.abspath(__file__)
    
    # Get Task Info
    cron_info = get_crontab_info()
    if cron_info == "Unable to read system crontab (Permission Denied or Empty). Please check manually.":
        # Simulate what the cron WOULD be based on cron_setup.sh
        cron_info = f"""(System crontab not readable)\nExpected Tasks based on setup:\n0 9 * * * python3 {project_root}/marketing/reddit_bot/report_tasks.py"""
    
    # Check if services are PAUSED
    paused_status = "🟢 Running"
    paused_file = os.path.join(os.path.dirname(__file__), "PAUSED")
    if os.path.exists(paused_file):
        paused_status = "🔴 PAUSED (Maintenance Mode)"

    payload = {
        "msg_type": "interactive",
        "card": {
            "config": {
                "wide_screen_mode": True
            },
            "header": {
                "title": {
                    "tag": "plain_text",
                    "content": "🤖 Daily Server Task Report"
                },
                "template": "blue"
            },
            "elements": [
                {
                    "tag": "div",
                    "fields": [
                        {
                            "is_short": True,
                            "text": {
                                "tag": "lark_md",
                                "content": f"**Time:**\n{current_time}"
                            }
                        },
                        {
                            "is_short": True,
                            "text": {
                                "tag": "lark_md",
                                "content": f"**Status:**\n{paused_status}"
                            }
                        }
                    ]
                },
                {
                    "tag": "div",
                    "text": {
                        "tag": "lark_md",
                        "content": f"**Project Root:**\n`{project_root}`"
                    }
                },
                {
                    "tag": "hr"
                },
                {
                    "tag": "div",
                    "text": {
                        "tag": "lark_md",
                        "content": "**📋 Active Crontab Tasks:**"
                    }
                },
                {
                    "tag": "div",
                    "text": {
                        "tag": "lark_md",
                        "content": f"```{cron_info}```"
                    }
                },
                {
                    "tag": "note",
                    "elements": [
                        {
                            "tag": "plain_text",
                            "content": f"Report generated by: {script_path}"
                        }
                    ]
                }
            ]
        }
    }

    try:
        response = requests.post(webhook_url, json=payload)
        if response.status_code == 200:
            print("Feishu report sent successfully.")
        else:
            print(f"Failed to send Feishu report: {response.text}")
    except Exception as e:
        print(f"Error sending report: {e}")

if __name__ == "__main__":
    send_feishu_report()
